# Generated by .github/workflows/release.yml on every tagged release.
# Edits here are overwritten; change the workflow instead.
class Lagerregal < Formula
  desc "Classify and browse your installed Homebrew packages by category"
  homepage "https://github.com/admonstrator/homebrew-lagerregal"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.5.0/lagerregal-0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "abf2ef5e1558e16905db3adb29e959ae2965d9dc59a28bc53258f7b50038f61a"
    end
    on_intel do
      url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.5.0/lagerregal-0.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "65f6680e8795d69ff19129d75cc9feb4f46af3b9b1461f3f657abbf42b5df92b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.5.0/lagerregal-0.5.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "1778b18dec13ca60901d2b96f3bfbe66ca05d974b23dd8132034e2f4247ee651"
    end
    on_intel do
      url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.5.0/lagerregal-0.5.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2633ad73f9644c3eb424e6911f416c6d66c16a6a57ddc733f03d13ec4a1f33db"
    end
  end

  def install
    bin.install "lagerregal"
  end

  test do
    assert_match "lagerregal", shell_output("#{bin}/lagerregal --version")
  end
end
