# Generated by homebrew-lagerregal's .github/workflows/release.yml on every tagged release.
# Edits here are overwritten; change that workflow instead.
class Lagerregal < Formula
  desc "Classify and browse your installed Homebrew packages by category"
  homepage "https://github.com/admonstrator/homebrew-lagerregal"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.4.0/lagerregal-0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "9bed2a09a3059ced6375383859c65f5802efddaade4f057e8eea2f0dac1b253d"
    end
    on_intel do
      url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.4.0/lagerregal-0.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "ace013f6f1dc356a17420ccdad525e34376bba25c5cbf0b4970911e0b4748bcb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.4.0/lagerregal-0.4.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "51d70a32510d8a8979350b8262257482acab88b3e55bbd8874c6c2cc4e4f84ef"
    end
    on_intel do
      url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.4.0/lagerregal-0.4.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "374d18bf16590316ec055a59f833a877fef82d98b60ff18693607f23b675c999"
    end
  end

  def install
    bin.install "lagerregal"
  end

  test do
    assert_match "lagerregal", shell_output("#{bin}/lagerregal --version")
  end
end
