# Generated by the manta release workflow — do not edit by hand.
class Manta < Formula
  desc "TUI network topology mapper for spanning-tree (STP/RSTP/MSTP/PVST+) networks"
  homepage "https://github.com/admonstrator/homebrew-spanningbrie"
  version "0.7.0"

  on_macos do
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.7.0/manta-v0.7.0-aarch64-apple-darwin.tar.gz"
      sha256 "a4f3b3cb8541a0389c9b0c68153ec19500fb696c3b09f136aff950a8618a77a4"
    end
  end

  on_linux do
    depends_on "libpcap"
    on_intel do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.7.0/manta-v0.7.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9235c33e93e617ff53f8f3f0acdc2e8008d6b5941a1f511aa6f573239ee985c9"
    end
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.7.0/manta-v0.7.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "820bb20938f98e95ab0bf786501ae6099e24df83f512b40592292b892be1b594"
    end
  end

  def install
    bin.install "manta"
  end

  test do
    assert_match "manta", shell_output("#{bin}/manta --version")
  end
end
