# Generated by the mantaray release workflow — do not edit by hand.
class Mantaray < Formula
  desc "TUI network topology mapper for spanning-tree (STP/RSTP/MSTP/PVST+) networks"
  homepage "https://github.com/admonstrator/manta"
  version "0.8.0"

  on_macos do
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.8.0/mantaray-v0.8.0-aarch64-apple-darwin.tar.gz"
      sha256 "d3066fc4f73633ee5fe0d46ee692172d63c71b26f26da57ecfaa78baa0bdb736"
    end
  end

  on_linux do
    depends_on "libpcap"
    on_intel do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.8.0/mantaray-v0.8.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "37a22ba7868f243fba8c1f30174cc52fe7d2dfcdf602451485e4fef78be35010"
    end
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.8.0/mantaray-v0.8.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a3766ed574b69a2b1e2efefbac42c70f7bf7c8a4edbd7336b3444538afc57e64"
    end
  end

  def install
    bin.install "mantaray"
  end

  test do
    assert_match "mantaray", shell_output("#{bin}/mantaray --version")
  end
end
