# Generated by the mantaray release workflow — do not edit by hand.
class Mantaray < Formula
  desc "TUI network topology mapper for spanning-tree (STP/RSTP/MSTP/PVST+) networks"
  homepage "https://github.com/admonstrator/mantaray"
  version "0.12.1"

  on_macos do
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.12.1/mantaray-v0.12.1-aarch64-apple-darwin.tar.gz"
      sha256 "92dfa928569e284c111e2eb4608862ada1116bffefa2a9d91070b0c0e00519f7"
    end
  end

  on_linux do
    depends_on "libpcap"
    on_intel do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.12.1/mantaray-v0.12.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d411c2d9f0e409a982eaf7ec5488bbc5df6e38a94598b75015403a91b7806076"
    end
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.12.1/mantaray-v0.12.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e64161ed3e95d19684b976d29444402ac1b271ffd30ec13f1df4cde1b03dc374"
    end
  end

  def install
    bin.install "mantaray"
  end

  test do
    assert_match "mantaray", shell_output("#{bin}/mantaray --version")
  end
end
