# Generated by the spanningbrie release workflow — do not edit by hand.
class Spanningbrie < Formula
  desc "TUI network topology mapper for spanning-tree (STP/RSTP/MSTP/PVST+) networks"
  homepage "https://github.com/admonstrator/homebrew-spanningbrie"
  version "0.6.0"

  on_macos do
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.6.0/spanningbrie-v0.6.0-aarch64-apple-darwin.tar.gz"
      sha256 "57b1fbd1c73f2b8cc5f700562c31e5ed03b44c0e31cf3e75f924e4706553a6eb"
    end
  end

  on_linux do
    depends_on "libpcap"
    on_intel do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.6.0/spanningbrie-v0.6.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6f0b6a4566b12b145f5b57d548fba9c2e1f9ac0e8b12d8b97647fb9393ef58c9"
    end
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.6.0/spanningbrie-v0.6.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e76ef0e498ec273601fc6e231db5f0a4315bf1b6ecf7c5a10877ca931cd5afe8"
    end
  end

  def install
    bin.install "spanningbrie"
  end

  test do
    assert_match "spanningbrie", shell_output("#{bin}/spanningbrie --version")
  end
end
