# Generated by the spanningbrie release workflow — do not edit by hand.
class Spanningbrie < Formula
  desc "TUI network topology mapper for spanning-tree (STP/RSTP/MSTP/PVST+) networks"
  homepage "https://github.com/admonstrator/homebrew-spanningbrie"
  version "0.4.0"

  on_macos do
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.4.0/spanningbrie-v0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "29273a8e378b8cb983bca6a631cf73e5423ac8fc59493866b02444269389d8ce"
    end
  end

  on_linux do
    depends_on "libpcap"
    on_intel do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.4.0/spanningbrie-v0.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b77f68b023be0e19e7b127dea4eeaebf167a70f64702bb3a30d304896a0720ca"
    end
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.4.0/spanningbrie-v0.4.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ee3db3f9b84a387a7c7558cd0693914aaea47d79fac1ff292d919d90658fbaaa"
    end
  end

  def install
    bin.install "spanningbrie"
  end

  test do
    assert_match "spanningbrie", shell_output("#{bin}/spanningbrie --version")
  end
end
