# Generated by the spanningbrie release workflow — do not edit by hand.
class Spanningbrie < Formula
  desc "TUI network topology mapper for spanning-tree (STP/RSTP/MSTP/PVST+) networks"
  homepage "https://github.com/admonstrator/homebrew-spanningbrie"
  version "0.3.0"

  on_macos do
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.3.0/spanningbrie-v0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "13b5241da1850adea22150f97bc96fed99f930002ac7af67865fa401fda8c4be"
    end
  end

  on_linux do
    depends_on "libpcap"
    on_intel do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.3.0/spanningbrie-v0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9f6faaa25e08d18302e3de6a87ab8cc112978b54074a260386925857007e0142"
    end
    on_arm do
      url "https://github.com/admonstrator/homebrew-tap/releases/download/v0.3.0/spanningbrie-v0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "682e98591806ccebc4fc69a6a84d838f50bc906ad7e73550f9959a53f180860f"
    end
  end

  def install
    bin.install "spanningbrie"
  end

  test do
    assert_match "spanningbrie", shell_output("#{bin}/spanningbrie --version")
  end
end
